//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kdh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public int QueId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string AuthorFirstName { get; set; }
        public string AuthorityFirstName { get; set; }
        public int PurposeId { get; set; }
    
        public virtual Purpos Purpos { get; set; }
    }
}
