//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kdh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public System.DateTime DateOfSurvey { get; set; }
        public string QualityService { get; set; }
        public string AverageVisit { get; set; }
        public string AppointmentIssue { get; set; }
        public string StaffRate { get; set; }
        public string Comment { get; set; }
    }
}
