CREATE TABLE [dbo].[DonationContacts] (
    [DonorId]      INT             IDENTITY (200, 1) NOT NULL,
    [FirstName]    VARCHAR (100)    NOT NULL,
    [LastName]     VARCHAR (100)    NOT NULL,
    [Email]        VARCHAR (50)    NOT NULL,
    [Phone]        VARCHAR (30)    NULL,
    [DonorAddress] VARCHAR (100)   NOT NULL,
    [City]         VARCHAR (20)    NOT NULL,
    [PostalCode]   CHAR (6)        NOT NULL,
    [Country]      VARCHAR (20)    NOT NULL,
    [Province]     VARCHAR (30)    NOT NULL,
    [Comments]     VARCHAR (900)   NULL,
    [DonationDate] DATETIME        CONSTRAINT [DonationContacts_DonationDate_df] DEFAULT (getdate()) NOT NULL,
    [Amount]       DECIMAL (20, 2) NOT NULL,
    [CreditCardId] INT NULL,
	CONSTRAINT [DonationContacts_CreditCardId_fk] FOREIGN KEY(CreditCardId) REFERENCES DonateCreditCards(CreditId),
    CONSTRAINT [DonationContacts_DonorId_pk] PRIMARY KEY CLUSTERED ([DonorId] ASC),
    CONSTRAINT [DonationContacts_FirstName_ck] CHECK (NOT [FirstName] like '%[^A-Za-z]%'),
    CONSTRAINT [DonationContacts_LastName_ck] CHECK (NOT [LastName] like '%[^A-Za-z]%'),
    CONSTRAINT [DonationContacts_Email_ck] CHECK ([Email] like '%___@___%.__%'),
    CONSTRAINT [DonationContacts_Phone_ck] CHECK ([Phone] like '[0-9][0-9][0-9][-][0-9][0-9][0-9][-][0-9][0-9][0-9][0-9]'),
    CONSTRAINT [DonationContacts_City_ck] CHECK (NOT [City] like '%[^A-Za-z]%'),
    CONSTRAINT [DonationContacts_PostalCode_ck] CHECK ([PostalCode] like '%[a-zA-Z][0-9][a-zA-Z][0-9][a-zA-Z][0-9]%'),
    CONSTRAINT [DonationContacts_Country_ck] CHECK (NOT [Country] like '%[^A-Za-z]%'),
    CONSTRAINT [DonationContacts_Province_ck] CHECK (NOT [Province] like '%[^A-Za-z]%')
);
