CREATE TABLE [dbo].[Patients]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(), 
    [FirstName] VARCHAR(50) NOT NULL, 
    [LastName] VARCHAR(50) NOT NULL, 
    [HealthCardNumber] VARCHAR(12) NULL, 
    [Address1] VARCHAR(100) NULL, 
    [Address2] VARCHAR(100) NULL, 
    [City] VARCHAR(20) NULL, 
    [Province] VARCHAR(20) NULL, 
    [PostalCode] VARCHAR(6) NULL, 
    [DateOfBirth] DATETIME2 NULL, 
    [Gender] VARCHAR(6) NOT NULL, 
    [Phone] VARCHAR(15) NULL, 
    [UserId] UNIQUEIDENTIFIER NULL, 
    [EmailToken] CHAR(64) NOT NULL, 
    [Status] VARCHAR(10) NOT NULL DEFAULT 'active', 
    CONSTRAINT [FK_Patients_Users] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id]), 
    CONSTRAINT [AK_Patients_EmailToken] UNIQUE ([EmailToken]),
	CONSTRAINT [CK_Patients_First_Name] CHECK (FirstName not like '%[^-.A-Z %''%]%'),
	CONSTRAINT [CK_Patients_Last_Name] CHECK (LastName not like '%[^-.A-Z %''%]%'),
	CONSTRAINT [CK_Patients_Health_Card_Num] CHECK (HealthCardNumber like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' OR HealthCardNumber like '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z][A-Z]'),
	CONSTRAINT [CK_Patients_Postal_Code] CHECK (PostalCode like '[A-Z][0-9][A-Z][0-9][A-Z][0-9]'),
	CONSTRAINT [CK_Patients_Gender] CHECK (Gender='Others' OR Gender='Female' OR Gender='Male'),
	CONSTRAINT [CK_Patients_Phone] CHECK ((Phone not like '%[^0-9]%' ) AND (DATALENGTH([Phone]))>9),
	CONSTRAINT [CK_Patients_Status] CHECK (Status='active' OR Status='inactive'),

)
